# Generated by Django 2.2 on 2019-04-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integree_test', '0002_auto_20190411_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'In progress'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default=1),
        ),
    ]
