# Generated by Django 2.2 on 2019-04-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integree_test', '0003_auto_20190411_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='description',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='subject',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
